import Footer from "@/components/products/Footer";
import Header from "@/components/products/Header";
import React from "react";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />

        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
